// THIS FILE WAS GENERATED BY A TOOL, DO NOT EDIT!

package main

import (
	"fmt"
	"log"
)

func main() {
	var err error
	var i int
	if i, err = NewForm(nil); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Done", i)
}
